### ISSUE TITLE
developer time locked

### ISSUE THREAD

**Issue by thiagolopes-dev** [datreks/codetime-vscode#25] opened 2022-09-08 14:54 UTC
I noticed that it is no longer counting the time since this period of 08/18/2022, it stuck at this value..

![Screenshot_14](https://user-images.githubusercontent.com/12428027/189154904-45b6540e-2dce-4cfb-9523-cd505ea1a0c3.png)

**Comment by Jannchie** [comment] 2023-02-17 18:09
I apologize for the delayed response. The issue was caused by an unreasonable back-end design, which I have now completely rewritten to prevent similar errors from happening again in the future. Your satisfaction is our top priority, and we are committed to providing you with the best possible service. Thank you for your patience and understanding.

**Closed by Jannchie** 2023-02-17 18:09 UTC
